### ISSUE TITLE
Some connections fail with TLS error

### ISSUE THREAD

**Issue by alxndrsn** [alxndrsn/pinchme#1]
E.g.: gemini://midnight.pub:

```
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Works fine with web proxy: https://portal.mozz.us/gemini/midnight.pub/

Checking in node REPL gives the same error:
```
s = tls.connect({ port:1965, host:'midnight.pub', enableTrace:true, minVersion:'TLSv1.2' });
s.once('error', err => console.log('err:', err));
s.once('secureConnect', () => console.log('connected!'));
```
->
```
err: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:548:15)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'midnight.pub',
  port: 1965,
  localAddress: undefined
```
Note that the client **_appears to be using TLS v1.0, despite being asked not to_** (see `minVersion` option at https://nodejs.org/api/tls.html):
```
Sent Record
Header:
  Version = TLS 1.0 (0x301)
  Content Type = Handshake (22)
  Length = 340
    ClientHello, Length=336
      client_version=0x303 (TLS 1.2)
...
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Alert (21)
  Length = 2
    Level=fatal(2), description=internal error(80)
```

**Comment by alxndrsn** [comment]
Clue?

```
$ openssl s_client -connect midnight.pub:1965
...
    Verify return code: 21 (unable to verify the first certificate)
...
```
